feat: new Auth's components and building SignUp page
dv-script/cardDrag-ts pull request #14
Opened 2023-05-31 01:39 UTC by dv-script

2023-05-31 09:33 UTC, AlexcastroDev requested changes

2023-05-31 09:33 UTC, AlexcastroDev commented on src/App.tsx
> +      {/* <RouteComponent /> */}
Não deveria apagar isto

2023-05-31 09:33 UTC, AlexcastroDev commented on src/App.tsx
> +      <Register />
Isto não deveria estar aqui

2023-05-31 09:33 UTC, AlexcastroDev commented on src/pages/Auth/components/LoginInput/style.ts
> +  font-family: "Poppins";
Não é necessário redeclarar font-family

2023-05-31 09:33 UTC, AlexcastroDev commented on src/pages/Auth/SignUp/index.tsx
> +            <LoginInput
Se o LoginInput é um input em comum, não deveria ser um LoginInput, e sim um componente global chamado apenas de `Input`, assim você consegue usar ele em vários lugares.

2023-05-31 16:07 UTC, dv-script commented on src/pages/Auth/components/LoginInput/style.ts
> +  font-family: "Poppins";
Quando eu tiro esse específico font-family, as configurações que coloco de font-size e font-weight não são consideradas. A alternativa que eu encontrei seria definir no GlobalStyle.ts que a tag button recebe a font-family Poppins. Posso fazer dessa forma?

2023-05-31 19:57 UTC, dv-script commented
Fiz as correções de conflito

2023-05-31 20:53 UTC, AlexcastroDev requested changes

2023-05-31 20:53 UTC, AlexcastroDev commented on src/GlobalStyle.ts
> -  html {
Por que essa alteração ? o * vai adicionar a todos elementos, o que não é correto. Por que um img, dialog teria um font-family ? aplicar somente no html já faz com que os elementos herdem essa propriedade.

2023-05-31 20:53 UTC, alexcastrodev commented on src/components/Input/types.ts
> +export interface IInput {
```suggestion
export interface IInput extends React.HTMLAttributes<HTMLInputElement> {
```

2023-05-31 20:53 UTC, AlexcastroDev commented on src/components/Input/types.ts
> +    inputPlaceHolder: string
Pode deletar este inputPlaceholder

2023-05-31 20:53 UTC, alexcastrodev commented on src/components/Input/index.tsx
> +export default function Input({ labelContent, inputPlaceHolder }:IInput) {
conforme o que sugeri na interface, você pode alterar este para:

```suggestion
export default function Input({ labelContent, ...props }:IInput) {
```

2023-05-31 20:53 UTC, AlexcastroDev commented on src/components/Input/index.tsx
> +            <Styled.Input placeholder={inputPlaceHolder} />
```suggestion
            <Styled.Input {...props} />
```

2023-05-31 20:53 UTC, alexcastrodev commented on src/components/Input/index.tsx
> +            <Styled.Input placeholder={inputPlaceHolder} />
tudo, exceto o LabelContent, será passado pra dentro do input

2023-05-31 20:53 UTC, AlexcastroDev commented on src/components/Input/types.ts
> +    labelContent: string
por que `labelContent`? e não apenas `label` ?

2023-06-01 00:01 UTC, dv-script commented on src/GlobalStyle.ts
> -  html {
Aplicando font-family apenas no html, a tag `<button> ` sobrepõe um font-family vazio. Por esse motivo apliquei a todas as classes.

2023-06-01 12:28 UTC, AlexcastroDev commented on src/GlobalStyle.ts
> -  html {
Está errado, deveria estar dentro do body conforme a documentação oficial: https://www.w3.org/TR/css-fonts-3/

Sugestão:
  body {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    background: rgb(255,255,255);
    background: radial-gradient(circle, rgba(255,255,255,1) 0%, rgba(119,40,193,1) 0%, rgba(109,52,189,1) 12%, rgba(37,136,162,1) 100%);
    font-family: "Poppins";
  }

2023-06-01 13:51 UTC, dv-script commented
@AlexcastroDev Corrigi os erros citados acima

2023-06-02 12:46 UTC, alexcastrodev commented
precisa rodar o prettier

2023-06-02 19:03 UTC, AlexcastroDev approved these changes

2023-06-02 19:03 UTC, AlexcastroDev approved these changes

2023-06-02 19:07 UTC, merged